version: "3.8"

services:
  bluemap-frontend:
    image: nginx:alpine
    container_name: bluemap-frontend
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    labels:
      - com.centurylinklabs.watchtower.enable=true
