import service from '@/utils/request'
export const getDuoCallAdmin = () => service({ url: '/duoCall/admin/list', method: 'get' })
export const saveDuoIdentity = (data) => service({ url: '/duoCall/admin/identity', method: 'post', data })
export const saveDuoStatus = (data) => service({ url: '/duoCall/admin/status', method: 'post', data })
export const deleteDuoStatus = (params) => service({ url: '/duoCall/admin/status', method: 'delete', params })
export const saveDuoAlbum = (data) => service({ url: '/duoCall/admin/album', method: 'post', data })
export const deleteDuoAlbum = (params) => service({ url: '/duoCall/admin/album', method: 'delete', params })
export const saveDuoAnniversary = (data) => service({ url: '/duoCall/admin/anniversary', method: 'post', data })
export const deleteDuoAnniversary = (params) => service({ url: '/duoCall/admin/anniversary', method: 'delete', params })
export const saveDuoAppRelease = (data) => service({ url: '/duoCall/admin/release', method: 'post', data })
export const deleteDuoAppRelease = (params) => service({ url: '/duoCall/admin/release', method: 'delete', params })
export const getDuoRitualAdmin = () => service({ url: '/duoCall/admin/ritual', method: 'get' })
export const saveDuoDailySetting = (data) => service({ url: '/duoCall/admin/ritual/setting', method: 'post', data })
export const saveDuoFallback = (data) => service({ url: '/duoCall/admin/ritual/fallback', method: 'post', data })
export const deleteDuoFallback = (params) => service({ url: '/duoCall/admin/ritual/fallback', method: 'delete', params })
export const regenerateDuoDaily = () => service({ url: '/duoCall/admin/ritual/regenerate', method: 'post' })
export const saveDuoWechatRecipient = (data) => service({ url: '/duoCall/admin/wechat/recipient', method: 'post', data })
export const testDuoWechatRecipient = (data) => service({ url: '/duoCall/admin/wechat/test', method: 'post', data })
export const retryDuoWechatPush = (data) => service({ url: '/duoCall/admin/wechat/retry', method: 'post', data })
