import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ICP_BEIAN_NO = "ICP备案/许可证号：";
const GONGAN_BEIAN_NO = "晋ICP备2026005636号";

export const metadata: Metadata = {
  title: "Charles's Home",
  description: "Generated by Charles's Home",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <footer className="fixed inset-x-0 bottom-3 z-30 flex flex-wrap items-center justify-center gap-x-4 gap-y-1 px-4 text-xs text-slate-500">
          <a
            href="https://beian.miit.gov.cn/"
            target="_blank"
            rel="noreferrer"
            className="transition hover:text-slate-800"
          >
            {ICP_BEIAN_NO}
          </a>
          <a
            href="https://beian.mps.gov.cn/"
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-1 transition hover:text-slate-800"
          >
            <img src="/beian/gongan.png" alt="" className="h-3.5 w-3.5" />
            <span>{GONGAN_BEIAN_NO}</span>
          </a>
        </footer>
      </body>
    </html>
  );
}
